#! /bin/bash
# Run autoQA gear

# Configure the ENV
export LD_LIBRARY_PATH=/opt/mcr/v97/runtime/glnxa64:/opt/mcr/v97/bin/glnxa64:/opt/mcr/v97/sys/os/glnxa64:$LD_LIBRARY_PATH

###############################################################################
# Configure paths
FLYWHEEL_BASE=/flywheel/v0
OUTPUT_DIR=$FLYWHEEL_BASE/output
INPUT_DIR=$FLYWHEEL_BASE/input
CONFIG_FILE=$FLYWHEEL_BASE/config.json
MANIFEST_FILE=$FLYWHEEL_BASE/manifest.json

###############################################################################
echo -e "Starting autoQA..."
# Set permissions for outputs (prevent root only r/w)
# chmod -R 777 $OUTPUT_DIR
# Run autoQA
$FLYWHEEL_BASE/autoQA
# Check status code and die
if [[ $? != 0 ]]; then
  echo -e "Problem encountered during autoQA!"
  exit 1
fi
echo -e "Done!"

exit 0